// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeVwV6FwlSCTJ63kw8phQ9oMh_1KXLFJM',
    appId: '1:951801310821:web:04cd3b01ac9fead77be08c',
    messagingSenderId: '951801310821',
    projectId: 'bookmyshow-568b3',
    authDomain: 'bookmyshow-568b3.firebaseapp.com',
    storageBucket: 'bookmyshow-568b3.firebasestorage.app',
    measurementId: 'G-L9DSWYLWP8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAE_J2Ni-xEVLm2OzEnTJPaHouTreGU2-c',
    appId: '1:951801310821:android:a3cbe5433ba854fe7be08c',
    messagingSenderId: '951801310821',
    projectId: 'bookmyshow-568b3',
    storageBucket: 'bookmyshow-568b3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLcAIxCY4SbuKof-dlfnO21J3iRKHavMQ',
    appId: '1:951801310821:ios:c6062871a3a417577be08c',
    messagingSenderId: '951801310821',
    projectId: 'bookmyshow-568b3',
    storageBucket: 'bookmyshow-568b3.firebasestorage.app',
    iosClientId: '951801310821-c17lb7h8njj6fq51nog03pjicfpm9g8k.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookmysht',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLcAIxCY4SbuKof-dlfnO21J3iRKHavMQ',
    appId: '1:951801310821:ios:c6062871a3a417577be08c',
    messagingSenderId: '951801310821',
    projectId: 'bookmyshow-568b3',
    storageBucket: 'bookmyshow-568b3.firebasestorage.app',
    iosClientId: '951801310821-c17lb7h8njj6fq51nog03pjicfpm9g8k.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookmysht',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeVwV6FwlSCTJ63kw8phQ9oMh_1KXLFJM',
    appId: '1:951801310821:web:ee624d82cdb9e7c97be08c',
    messagingSenderId: '951801310821',
    projectId: 'bookmyshow-568b3',
    authDomain: 'bookmyshow-568b3.firebaseapp.com',
    storageBucket: 'bookmyshow-568b3.firebasestorage.app',
    measurementId: 'G-B3KXHJRLP0',
  );

}